version: 2
workflows:
  version: 2
  main:
    jobs:
      - blackwater-session-notes
      - release-notes:
          requires:
            - blackwater-session-notes
jobs:
  blackwater-session-notes:
    docker:
      - image: rickosborne/pandoc-crossref:0.3.4.1a
    steps:
      - run:
          name: Install Git/OpenSSH
          command: apk -U add git openssh
      - checkout
      - run:
          name: Make target dir
          command: mkdir -p /target
      - run:
          name: Compile md to docx
          command: >
            pandoc blackwater/sessions/*.md \
              -f markdown+smart+fenced_divs+raw_attribute+backtick_code_blocks \
              -t docx \
              --filter pandoc-crossref \
              --number-sections \
              -s --self-contained \
              --reference-doc tool/doc-from-md/template.docx \
              --no-highlight \
              --listings \
              --reference-links \
              -o /target/blackwater-session-notes.docx
      - save_cache:
          key: blackwater-session-notes-{{ checksum "/target/blackwater-session-notes.docx" }}
          paths:
            - /target/blackwater-session-notes.docx
#      - store_artifacts:
#          path: /target/blackwater-session-notes.docx
#          name: blackwater-session-notes.docx

  release-notes:
    docker:
      - image: tsub/ghr
    steps:
#      - attach_workspace:
#          at: /target
      - restore_cache:
          key: blackwater-session-notes-
      - run:
          command: >
            ghr \
              -t "${GITHUB_TOKEN}" \
              -u "${CIRCLE_PROJECT_USERNAME}" \
              -r "${CIRCLE_PROJECT_REPONAME}" \
              -c "${CIRCLE_SHA1}" \
              -delete $(date +'%Y%m%d%H%M%S') \
              /target/blackwater-session-notes.docx
